JNG-4184 Fix single static navigation
BlackBeltTechnology/judo-meta-query pull request #45
Opened 2023-01-18 15:47 UTC by bencegelei

2023-01-18 17:29 UTC, robertcsakany requested changes

2023-01-18 17:29 UTC, robertcsakany commented on model/model/query.aird
>  <?xml version="1.0" encoding="UTF-8"?>
There is no metamodel change, so AIRD file cannot change

2023-01-18 17:36 UTC, noherczeg approved these changes

2023-01-18 20:25 UTC, bencegelei commented on model/model/query.aird
>  <?xml version="1.0" encoding="UTF-8"?>
I can revert it if it's really necessary, but it includes some "visual" improvements on the diagram. Small changes, but improves the readability of the mode.

2023-01-19 07:26 UTC, robertcsakany commented on model/model/query.aird
>  <?xml version="1.0" encoding="UTF-8"?>
Then its OK, stays.

2023-01-19 07:26 UTC, robertcsakany approved these changes

2023-01-24 11:05 UTC, merged