JNG-4504 Release judo meta query
BlackBeltTechnology/judo-meta-query pull request #51
Opened 2023-02-28 14:17 UTC by gaborflorian

2023-02-28 14:55 UTC, noherczeg approved these changes

2023-02-28 21:42 UTC, bencegelei requested changes

2023-02-28 21:42 UTC, bencegelei commented on pom.xml
> +				<version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:38 UTC, gaborflorian commented on pom.xml
> +				<version>1.2.11</version>
Requested by Robert

2023-03-01 10:09 UTC, robertcsakany approved these changes

2023-03-01 11:54 UTC, bencegelei approved these changes

2023-03-09 10:25 UTC, merged